### ISSUE TITLE
Creating API functions

### ISSUE THREAD

**Issue by jeroendesloovere** [megasnort/fork-cms-module-elo-rating#15]
Hi,

It would be awesome if there were API functions available.
So an iOS-app could communicate with it.

**Comment by megasnort** [comment]
Feel free to make a pull request, but I won't I add them myself.

**Comment by jeroendesloovere** [comment]
@megasnort Ok, thanks for the reply.
Currently I have no need for such a feature, but who knows, maby in the future.
