### ISSUE TITLE
ELO rating

### ISSUE THREAD

**Issue by Cu8eR** [megasnort/fork-cms-module-elo-rating#16]
Is possible to show how the ELO rating is changed after each games?

Now we can see  player user name vs opponent user name III results III date - what about ELO +-?

**Comment by megasnort** [comment]
If you go to a player's profile (who has played enough games): f.e. http://schakenopviso.megasnort.com/ranking/speler/s--bastiaansen you can position your mouse above the bullet in the graph to see the Elo- at that time 
![title](https://cloud.githubusercontent.com/assets/736827/5658043/d04c6650-96fa-11e4-8f33-b0a07de27e04.PNG)

**Comment by Cu8eR** [comment]
Yes, you are right but it would be better to show ELO change in every game (+ or -)

**Comment by Cu8eR** [comment]
Here is my idea:
![elo_change](https://cloud.githubusercontent.com/assets/778890/5659248/60d32290-970f-11e4-854c-2f9be4bb2beb.png)

I think it is really useful. Or could you help me how to add it?

**Comment by megasnort** [comment]
Hmm. Might indeed be a good idea. 
This data is cached in the elo_history-table, so I shouldn't be that hard to figure it out. Probably walking the games and history at the same time would do the trick, since they have the the same length.

Feel free to make a pull request. Or if you can wait, I'll make the modification when I have the time.

**Comment by Cu8eR** [comment]
I will wait, thank you very much!

**Comment by megasnort** [comment]
I'll see what I can do.

**Comment by Cu8eR** [comment]
@megasnort - nice, I see that you added this into your module. It looks good. 

Is there any easy way how to show the number in brackets:
- possitive elo changes in green color
- negative elo changes in red color

**Comment by megasnort** [comment]
Done.
Note that I also just fixed a major bug in the calculations of the Elo-ratings (a bracket that was out of place). Winners got way to much points. If you just edit a single game, all ratings will be recalculated correctly.

**Comment by Cu8eR** [comment]
Thank you, now it looks amazing!
