### ISSUE TITLE
Game statistics - opponnent

### ISSUE THREAD

**Issue by Cu8eR** [megasnort/fork-cms-module-elo-rating#18]
Show game history in profile for specific opponent. For example:

Last games against XXX:
13.1.2014 xxxxx
20. 1. 2015 xxxx

etc

**Comment by megasnort** [comment]
Perhaps a separate action where two opponents can be compared would be better.

Url would be something like
.../compare/*name_player1*/to/*name_player2*

On the page, itself, the selects are visible where the users in the url are selected

**Comment by Cu8eR** [comment]
Hmm, could you tell me how to achieve this? Thanky

**Comment by megasnort** [comment]
I'll make it myself. If you have the time, again. :)
(Out of interest, where will you use the module for?)

**Comment by Cu8eR** [comment]
I modified it a little and we use it for tournament in Carcassonne game. I
have another ideas how to improve it, this is one of the best module.
Dne 8. 1. 2015 13:26 "Stef Bastiaansen" <notifications@github.com>
napsal(a):

**Comment by megasnort** [comment]
Cool!
I'll try to keep the database-structure intact see you can just copy the new files over the old ones.

**Comment by Cu8eR** [comment]
Dont worry, I can solve this issue

**Comment by megasnort** [comment]
I had an epiphany and realized I could add this quite easily. Check the <select> on http://schakenopviso.megasnort.com/ranking/speler/s--bastiaansen
No database modifications were necessary so you can just copy the new module files, although you probably want to add the word 'against' to the label {lblPlayersGames}

**Comment by Cu8eR** [comment]
IT is not working for me (at least on your website). I can choose an opponent name but nothing happens

**Comment by megasnort** [comment]
You need to clear your cache (SHIFT + refresh did the trick for me.) The showing/hiding is done with Javascript.

**Comment by Cu8eR** [comment]
OK, now it is OK - maybe just align "select" to the right 

(I know, I can edit it manualy but it is only an idea)
