### ISSUE TITLE
Add winrate/drawrate and lost rate in %

### ISSUE THREAD

**Issue by Cu8eR** [megasnort/fork-cms-module-elo-rating#20]
It would be nice to show win/draw/lost rate in % for every user. Now we can see only how many, but not in %

I think it is easy to add and really useful

**Comment by Cu8eR** [comment]
+ also add total games played 
(now you have to check ranking page, it should be shown also in player profile)

**Comment by megasnort** [comment]
It's visible on top of the profile (http://schakenopviso.megasnort.com/ranking/speler/j--mone) in the description. (although you have to do some math)

**Comment by megasnort** [comment]
About, the win/lost rate in percentages, I don't think adding this provides more clarity. It's just more info. I have got to stop somewhere :)

**Comment by Cu8eR** [comment]
OK, so what about to add this:

Player has an Elo rating of 1535 and is ranked at position 1.
Player played 10 games in total - won 6 games, lost 4 and played a draw 0 times. Win rate is 60 %.

ELO rating and possition should be bolded. 


php code for this:
  function WinningPercentage($wins, $losses){ 
      return round(($wins / ($wins + $losses)) *100), 1).'%'; 
  }

**Comment by Cu8eR** [comment]
Thank you!
