### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by Cu8eR** [megasnort/fork-cms-module-elo-rating#21]
Is possible to use d/m/year date format for games? For example 5th january 2015 - 5/1/2015 without leading zero before day

Same for

**Comment by Cu8eR** [comment]
Jut to clarify this issue:
use short date format set in CMS in general settings

**Comment by megasnort** [comment]
Shouldn't be a problem. I'll add it to the list.

**Comment by megasnort** [comment]
You can fix this manually, in the database look in the module_settings tabel for the setting 'date_format_long'
![schermafbeelding 2015-01-10 om 13 41 48](https://cloud.githubusercontent.com/assets/736827/5691578/9105c628-98ce-11e4-9376-cade8da211eb.PNG)

Change it according to http://php.net/manual/en/function.date.php. Note that the number after the 's:' should be the number of characters of your date format

Tip: You might want to add it to to the 'date_format*s*_long' setting too, so your customs setting won't be erased after you update your setting in the backend.

**Comment by Cu8eR** [comment]
Thank you. I think this module should use time format (long and short) according to settings in general tab in fork cms.

**Comment by Cu8eR** [comment]
OK, I propably found a bug:

- frontend module/widget follow my date/time setting. However date in "Add a game" widget is not follow this setting. It shows a leading zero before date and month

**Comment by megasnort** [comment]
You mean in the textfield? This is not a bug. The date needs to be formatted in a certain way (xx/xx/xxxx) for easy processing when adding a game. I chose for a format with a leading zero.
