### ISSUE TITLE
Add a filter into games played page

### ISSUE THREAD

**Issue by Cu8eR** [megasnort/fork-cms-module-elo-rating#22]
Add a range filter for date in games played page (for example show all games from 11.10.2014 to 24.12.2014).

**Comment by megasnort** [comment]
Might be a good idea. I'll keep the issue open, but not gonna add it anytime soon.

Also, do you have a public link to your Carcassonne website, and would you find it ok if I make a link to it as an example in the [README.md](https://github.com/megasnort/fork-cms-module-elo-rating/blob/master/README.md)?

**Comment by Cu8eR** [comment]
About the link - of course, you can add link to my carcasonne website.

I just need to figure out last 3 things before the website go live. We use old webpage (manually added elo changes, etc). So we will transfer all played games to a new system based on your module.

I just need to solve last 3 issues:
- change date/time format
- add winrate and total games into player´s info - I will have to find the easiest way how to do it
- add my translation (almost done)

**Comment by megasnort** [comment]
The first thing you can do yourself manually in the database. I'll try to include the win/loss rate in the players profile sometime soon.
And are you making the translation as a translation file? That would be cool to include in the Repo. Be sure to send it as a pull request.

**Comment by Cu8eR** [comment]
@megasnort - yes I will push my PR with translation

I have a problem - how to change date format? I cannot open the module_setting in phpamyadmin

**Comment by megasnort** [comment]
![schermafbeelding 2015-02-06 om 08 21 15](https://cloud.githubusercontent.com/assets/736827/6075749/2c750b7c-add9-11e4-834e-59dc97beb21d.PNG)

**Comment by Cu8eR** [comment]
@megasnort - I cannot open this table :( I think it is a problem of myphp.

What about to manually change it in template? You use long format date, is possible to use short format date?
