### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by Cu8eR** [megasnort/fork-cms-module-elo-rating#24]
I updated to the last version (with new features) - but I get errors when I click on a player name in game played/ranked or when I wanna add a game into DB

**Comment by megasnort** [comment]
You have add the 'game' field (INT) to 'elo_history'-table.

**Comment by Cu8eR** [comment]
I added it. I can see user profile, but there is only stats (wins, games. standing), no game history etc

![elo_problem](https://cloud.githubusercontent.com/assets/778890/5694957/a8c77f6c-9983-11e4-86eb-07a11b3d31fe.png)

**Comment by megasnort** [comment]
Oh yeah, you have to go to the backend, open a game there (f.e. .../private/nl/elo_rating/edit?id=1), and save it so the elo_history-table is re-filled.

If this doesn't work: Did you update frontend AND backend-files? Also, try to clear the cache (./tools/remove_cache)

**Comment by Cu8eR** [comment]
Yes, I updated all files with your latest code from github.

Now I can see stats but I dont see any ELO change collumn. I will check it later

**Comment by megasnort** [comment]
Should look like the last column here: http://schakenopviso.megasnort.com/ranking/speler/s--bastiaansen

**Comment by Cu8eR** [comment]
I think there must be a problem in my CMS - I will try your updated module on new fresh instalation.

**Comment by megasnort** [comment]
Normally really shouldn't be necessary. Except this one database field nothing really changed. Can you perhaps send me a dump of your current database? (stef@megasnort.com)

**Comment by Cu8eR** [comment]
Give me some time - I am working on it

**Comment by Cu8eR** [comment]
FIXED! Thank you. It was my mistake - I missed one folder in /cache/
