### ISSUE TITLE
Bug in statistic page

### ISSUE THREAD

**Issue by Cu8eR** [megasnort/fork-cms-module-elo-rating#29]
Hi,

there is a bug

link:
http://carcassonnecup.4fan.cz/hodnocen-iacute/player/eldenroot

This user has played 4 games - 1 won, 0 draw, 3 lost - but there is a text: won 4, ...

**Comment by megasnort** [comment]
Thanks!

**Comment by Cu8eR** [comment]
You are welcome :)
