### ISSUE TITLE
Issue with special characters in players name

### ISSUE THREAD

**Issue by Cu8eR** [megasnort/fork-cms-module-elo-rating#32]
There is a problem with special characters in players name.

For example: username "šmoula" -> he is saved into DB, he is shown in the widget but when you click on his name -> 404 error page. Only rename to "smoula" helps

there should be a check for url generating or special characters should be disabled in usernames

**Comment by megasnort** [comment]
Hmm. This should be working (speciale characters are deleted). At least, it works here. Can you perhaps send me a database dump?

**Comment by Cu8eR** [comment]
@megasnort - feel free to try it: http://carcassonnecup.4fan.cz/

username: "šmoula" -> 404 error

How to fix? Just rename this user to "smoula"

**Comment by megasnort** [comment]
Hmmm. Must have something to do with your locale ... I'll give it a look.

**Comment by Cu8eR** [comment]
But there is no problem when the special character is in the middle of the username

for example username "peťul" is working fine, the special character is not in url 
http://carcassonnecup.4fan.cz/hodnocen-iacute/player/peul

**Comment by megasnort** [comment]
I didn't replace all funny characters. I'm using the iconv-php function now, should be better now.

**Comment by Cu8eR** [comment]
I uploaded latest version on my site... problem persists

**Comment by megasnort** [comment]
Did you save the player again?

**Comment by Cu8eR** [comment]
Yes, I did... I renamed him and than change to his real name
